name: build


on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: Install dependencies 
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'
          cache: 'npm'
      - name: Build angular app
        run: npm run build
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_dist
          path: dist/
          cache: 'npm'
  deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
          - name: Checkout
            uses: actions/checkout@v2
            with:
              ref: gh-pages
          - name: Download build
            uses: actions/download-artifact@v1
            with:
              name: deploy_dist
          - name: Tree list
            run: tree
          - name: Deploy to GitHub Pages
            uses: JamesIves/github-pages-deploy-action@v4.2.5
            with:
              BRANCH: gh-pages
              FOLDER: deploy_dist/dist/dcms-g6
